#!/usr/bin/env python3
"""Собрать конфиг fastfetch под текущую палитру обоев.

Отдельным скриптом, а не шаблоном matugen: fastfetch ждёт цвет голыми
числами в виде "38;2;R;G;B", а matugen подставляет "rgb(R, G, B)" — с
такой строкой fastfetch цвет не разбирает.

Без этого файла у fastfetch конфига не было вовсе, и он красился цветами
логотипа Arch по умолчанию, никак не следуя за обоями.
"""
import colorsys
import json
import os
import re

PALETTE = os.path.expanduser("~/.cache/matugen/colors.css")
OUT = os.path.expanduser("~/.config/fastfetch/config.jsonc")


def hexof(name, fallback="#cccccc"):
    try:
        css = open(PALETTE).read()
    except OSError:
        css = ""
    m = re.search(r"@define-color\s+%s\s+#([0-9a-fA-F]{6})" % re.escape(name), css)
    return m.group(1) if m else fallback.lstrip("#")


def shade(h, lightness):
    """Тот же оттенок, другая светлота (0..1) — чтобы цвета были одной семьи."""
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    hue, _, sat = colorsys.rgb_to_hls(r, g, b)
    r, g, b = colorsys.hls_to_rgb(hue, max(0.0, min(1.0, lightness)), sat)
    return "%02x%02x%02x" % (round(r * 255), round(g * 255), round(b * 255))


def seq(h):
    return ";".join(str(int(h[i:i + 2], 16)) for i in (0, 2, 4))


def rgb(name, fallback="#cccccc"):
    try:
        css = open(PALETTE).read()
    except OSError:
        css = ""
    m = re.search(r"@define-color\s+%s\s+#([0-9a-fA-F]{6})" % re.escape(name), css)
    h = m.group(1) if m else fallback.lstrip("#")
    return ";".join(str(int(h[i:i + 2], 16)) for i in (0, 2, 4))


def main():
    # Все цвета — из ОДНОГО оттенка акцента, разной светлоты. Раньше брались
    # три роли палитры (primary/secondary/tertiary), а у схемы vibrant их
    # оттенки расходятся: логотип выходил голубым, заголовок — сиреневым, и
    # вывод смотрелся разнородным (замечено пользователем 21.09.2026).
    accent = hexof("primary")
    prim = seq(accent)
    # 22.09.2026: второй цвет логотипа = первому. Раньше стоял тот же тон
    # темнее (shade 0.72), и логотип Arch выходил двухцветным — пользователь просил
    # один цвет.
    sec = prim
    tert = seq(shade(accent, 0.92))      # заголовок — тот же тон светлее
    text = seq(hexof("on-surface"))      # значения — обычный текст палитры
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    # Список модулей обязателен. Как только появляется файл конфига,
    # fastfetch перестаёт применять набор по умолчанию и выводит ТОЛЬКО
    # перечисленное — без этого блока остаётся один логотип без текста.
    # 23.09.2026: у четырёх самых длинных модулей свой укороченный формат.
    # Причина — строка вида «Font PxPlus HP 100LX 6x8 (12pt) [Qt], PxPlus HP
    # 100LX 6x8 (12pt) [GTK2/3/4]» (76 знаков): рядом с логотипом Arch (54
    # колонки) она не помещалась, терминал переносил хвост, и тот ложился
    # поверх логотипа. Логотип при этом остаётся полным — его пользователь просил
    # не трогать; остаток, если окно совсем узкое, обрезается по краю
    # (nowrap), а не переносится.
    modules = ["title", "separator", "os", "host", "kernel", "uptime",
               "packages", "shell",
               # был весь список экранов с герцами и дюймами
               {"type": "display", "format": "{width}x{height} @ {refresh-rate} Hz"},
               "wm", "theme", "icons",
               # был и Qt, и GTK — теперь только первый шрифт
               {"type": "font", "format": "{font1}"},
               "cursor", "terminal", "terminalfont",
               # была ещё частота: «(8+4) @ 4.40 GHz»
               {"type": "cpu", "format": "{name} ({cores-logical})"},
               # был тип в скобках: «[Discrete]»
               {"type": "gpu", "format": "{name}"},
               "memory", "swap", "break", "colors"]
    body = ",\n    ".join(m if isinstance(m, str) and False else
                          ('"%s"' % m if isinstance(m, str) else json.dumps(m, ensure_ascii=False))
                          for m in modules)
    with open(OUT, "w") as f:
        f.write("""// Generated by fastfetch_colors.py — do not edit
{
  "logo": { "color": { "1": "38;2;%s", "2": "38;2;%s" } },
  "display": {
    "color": { "keys": "38;2;%s", "title": "38;2;%s", "output": "38;2;%s" },
    "separator": " "
  },
  "modules": [
    %s
  ]
}
""" % (prim, sec, prim, tert, text, body))
    print("fastfetch: акцент=%s заголовок=%s значения=%s" % (prim, tert, text))


if __name__ == "__main__":
    main()
