#!/usr/bin/env python3
"""Подмешать оттенок обоев в фоны приложений GTK4 (libadwaita).

Зачем: схема scheme-fidelity делает тёмные поверхности почти нейтральными —
у window_bg_color насыщенность около 17% при яркости 9%, то есть это
практически чёрный. Тон правильный, но глазом синевы не видно, и окна
выглядят чужими на цветных обоях.

Здесь фонам поднимается насыщенность и навязывается тон акцента. ЯРКОСТЬ НЕ
ТРОГАЕТСЯ: если её поднять, тёмная тема перестанет быть тёмной, а контраст
с текстом упадёт.

Правка живёт отдельным файлом, который подключается ПОСЛЕ matugen.css.
Так она касается только GTK4 и переживает пересборку палитры.
"""
import colorsys
import os
import re

SRC = os.path.expanduser("~/.config/gtk-4.0/matugen.css")
OUT = os.path.expanduser("~/.config/gtk-4.0/tint.css")

# Насколько насыщенным делать фон. 0.38 подобрано так, чтобы оттенок читался,
# но поверхность оставалась спокойной и не спорила с содержимым окна.
SAT = 0.38
TARGETS = ("window_bg_color", "view_bg_color", "headerbar_bg_color",
           "popover_bg_color", "dialog_bg_color", "card_bg_color",
           "sidebar_bg_color", "secondary_sidebar_bg_color")


def read(css, name):
    m = re.search(r"@define-color\s+%s\s+#([0-9a-fA-F]{6})" % re.escape(name), css)
    return m.group(1) if m else None


def main():
    try:
        css = open(SRC).read()
    except OSError:
        return 1

    acc = read(css, "accent_color") or "7aa2f7"
    ar, ag, ab = (int(acc[i:i + 2], 16) / 255 for i in (0, 2, 4))
    hue = colorsys.rgb_to_hsv(ar, ag, ab)[0]

    lines = ["/* Generated by gtk_tint.py — do not edit */"]
    for name in TARGETS:
        hexv = read(css, name)
        if not hexv:
            continue
        r, g, b = (int(hexv[i:i + 2], 16) / 255 for i in (0, 2, 4))
        _, _, v = colorsys.rgb_to_hsv(r, g, b)
        nr, ng, nb = colorsys.hsv_to_rgb(hue, SAT, v)   # яркость v сохранена
        lines.append("@define-color %s #%02x%02x%02x;"
                     % (name, round(nr * 255), round(ng * 255), round(nb * 255)))

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("подкрашено переменных: %d, тон %d°" % (len(lines) - 1, round(hue * 360)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
