#!/usr/bin/env python3
"""Fixed blue/purple/red hues for the CPU/RAM/temperature bar modules, plus a
"vivid" accent for elements that were reading as plain white.

Material You's `primary` role sits around 84% lightness in dark schemes, and
`on_surface` around 91% — technically tinted, but light enough that the eye
just calls them white. That is why cava and the termdown countdown looked
colourless whatever the wallpaper. @vivid keeps the wallpaper's own hue but
drops lightness and holds saturation up, so the colour is actually legible as
a colour.

Hues are now DERIVED FROM THE WALLPAPER (11.09.2026). Before that they were
fixed (blue/purple/red) on the user's earlier request, after the wallpaper
triad came out pink/peach/yellow; the newer, absolute rule is that no element
may fall outside the wallpaper palette. So the three sensors sit on the
wallpaper's own hue, spread by HUE_OFFSETS degrees so they stay distinct
without leaving its colour family. Saturation/lightness still come from the
palette machinery below (clamped, never garish).
"""
import colorsys
import os

FACTS = os.path.expanduser("~/.cache/matugen/term-facts.sh")
OUT = os.path.expanduser("~/.cache/matugen/sensor-colors.css")


def read_facts():
    facts = {}
    try:
        for line in open(FACTS):
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                facts[k] = v.strip()
    except OSError:
        pass
    return facts


def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))


def rgb_to_hex(rgb):
    return "#%02x%02x%02x" % tuple(max(0, min(255, round(c * 255))) for c in rgb)


# Offsets from the wallpaper's hue, in degrees. CPU is the hue itself; RAM and
# temperature step 40 degrees either side — far enough apart to tell at a
# glance, close enough to stay in the wallpaper's colour family. (Fixed
# hues 221/271/8 before 11.09.2026, see the docstring.)
HUE_OFFSETS = {"sensor-cpu": 0, "sensor-mem": 40, "sensor-temp": -40}

# Lightness/saturation for @vivid. 68% lightness still reads clearly against
# the dark surfaces while being far enough from white to show its hue.
VIVID_LIGHT = 0.68
VIVID_SAT_MIN, VIVID_SAT_MAX = 0.55, 0.85
BORDER_LIGHT, BORDER_SAT = 0.55, 0.32     # рамка окон niri, см. main()


def main():
    f = read_facts()

    sat = max(0.30, min(0.55, float(f.get("ACCENT_SAT", 60)) / 100))
    light = 0.72

    lines = ["/* Generated by sensor_colors.py — do not edit */"]
    base_hue = float(f.get("ACCENT_HUE", 220))
    for name, off in HUE_OFFSETS.items():
        hue = (base_hue + off) % 360
        rgb = colorsys.hls_to_rgb(hue / 360, light, sat)
        lines.append(f"@define-color {name} {rgb_to_hex(rgb)};")

    # Wallpaper's own hue, but actually saturated — see the module docstring.
    accent_hue = float(f.get("ACCENT_HUE", 220))
    vivid_sat = max(VIVID_SAT_MIN,
                    min(VIVID_SAT_MAX, float(f.get("ACCENT_SAT", 70)) / 100))
    vivid = colorsys.hls_to_rgb(accent_hue / 360, VIVID_LIGHT, vivid_sat)
    lines.append(f"@define-color vivid {rgb_to_hex(vivid)};")

    # Подложка панели: оттенок обоев, но тёмный. @background от matugen
    # почти нейтрален (насыщенность ~9%), и на плотной заливке панель
    # выглядела просто серой. Здесь светлота низкая ради контраста с текстом,
    # а насыщенность держится высокой, чтобы гамма обоев читалась.
    # 16.09.2026: 0.11/0.45 -> 0.09/0.85 — пользователь просил панель темнее и
    # отчётливо тёмно-синей. Светлота вниз даёт темноту, насыщенность вверх —
    # чтобы на такой светлоте цвет вообще читался: при 0.45 подложка уходит
    # в серо-синий. Проверено на текущем акценте (226°): #0f1529 -> #030d2a,
    # на экране под баром (alpha 0.86 поверх размытых обоев) #222a4a -> ~#152048,
    # контраст с текстом панели остаётся выше 12:1.
    bar_bg = colorsys.hls_to_rgb(accent_hue / 360, 0.09, 0.85)
    lines.append(f"@define-color bar-bg {rgb_to_hex(bar_bg)};")

    # Рамка активного окна niri (08.10.2026, Просьба: «на уровне этого скрина» — рамка angelOS
    # #6a70ae). Пастельный primary (#b4c5ff) даже на 100 % выглядел белёсым: на образце цвет
    # не светлее, а насыщеннее. Тот же оттенок обоев, светлота 0.55, насыщенность 0.32,
    # без прозрачности. matugen к этому моменту уже собрал niri-colors.kdl (theme_changer.sh) —
    # здесь подменяется только active-color; неактивная остаётся из шаблона.
    border = colorsys.hls_to_rgb(accent_hue / 360, BORDER_LIGHT, BORDER_SAT)
    niri_colors = os.path.expanduser("~/.cache/matugen/niri-colors.kdl")
    try:
        import re
        txt = open(niri_colors).read()
        new = re.sub(r'(\n\s*active-color )"[^"]*"', r'\1"%s"' % rgb_to_hex(border), txt, count=1)
        if new != txt:
            open(niri_colors, "w").write(new)
    except OSError:
        pass

    # Same colour for consumers that need a plain hex file (termdown wrapper).
    with open(os.path.expanduser("~/.cache/matugen/vivid.txt"), "w") as fh:
        fh.write(rgb_to_hex(vivid) + "\n")

    open(OUT, "w").write("\n".join(lines) + "\n")

    # Для swaync (01.10.2026): та же тёмная подложка, что у баров и попапов, —
    # фон уведомлений из гаммы обоев, а не серый (--noti-bg-darker от matugen
    # почти нейтрален). swaync — GTK4, переменные CSS, поэтому :root.
    with open(os.path.expanduser("~/.cache/matugen/swaync-accent.css"), "w") as fh:
        fh.write("/* Generated by sensor_colors.py — do not edit */\n"
                 ":root {\n  --bar-bg: %s;\n  --vivid: %s;\n}\n"
                 % (rgb_to_hex(bar_bg), rgb_to_hex(vivid)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
