#!/usr/bin/env python3
"""Стеклянная тема YouTube Music Desktop в цветах обоев.

Приложение следит за файлом из своего config.json → appearance.customCSSPath
и переподставляет его на лету, так что цвета доезжают без перезапуска.

ПРАВИМ МИНИМАЛЬНО. Первая версия скрипта переписывала файл целиком и заодно
подменяла переменные YouTube Music (--ytmusic-color-black* и прочие) — это
сломало вёрстку: верх страницы стал светлым, боковое меню наехало на контент.
Поэтому теперь берётся исходная тема пользователя как есть
(templates/ytm-glass.orig.css) и в ней заменяются ТОЛЬКО базовые цвета
подложек: вместо зашитого тёмно-синего — поверхность текущей палитры с той же
прозрачностью. Ни одного селектора и ни одной новой строки не добавляется.
"""
import json
import os
import re
import sys

BASE = os.environ.get("YTM_BASE", os.path.expanduser(
    "~/.config/matugen/templates/ytm-glass.orig.css"))
PALETTE = os.environ.get("YTM_PALETTE",
                         os.path.expanduser("~/.cache/matugen/colors.json"))
OUT = os.environ.get("YTM_OUT", os.path.expanduser("~/.config/hypr/ytm-glass.css"))

# Какой ролью палитры заменять каждый зашитый цвет исходной темы.
# Ключ — цвет в оригинале, значение — роль. Прозрачность берётся из оригинала.
SUBST = {
    (10, 12, 22): "surface",           # общая подложка окна
    (15, 17, 26): "surface_lowest",    # поисковая строка и плеер
    (255, 255, 255): "on_surface",     # тонкие разделительные линии
}


def main():
    try:
        base = open(BASE, encoding="utf-8").read()
        with open(PALETTE, encoding="utf-8") as f:
            p = json.load(f)
    except OSError as e:
        print("ytm_colors: %s" % e, file=sys.stderr)
        return 1

    def repl(m):
        r, g, b, a = int(m.group(1)), int(m.group(2)), int(m.group(3)), m.group(4)
        role = SUBST.get((r, g, b))
        if role is None:
            return m.group(0)
        c = p[role].lstrip("#")
        nr, ng, nb = (int(c[i:i + 2], 16) for i in (0, 2, 4))
        return "rgba(%d, %d, %d, %s)" % (nr, ng, nb, a)

    out, n = re.subn(r"rgba\((\d+),\s*(\d+),\s*(\d+),\s*([0-9.]+)\)", repl, base)
    header = ("/* Generated by ytm_colors.py — do not edit.\n"
              " * Исходник: ~/.config/matugen/templates/ytm-glass.orig.css\n"
              " * Заменены только цвета подложек, вёрстка не тронута.\n"
              " */\n")
    open(OUT, "w", encoding="utf-8").write(header + out)
    print("ytm_colors: заменено цветов: %d, поверхность %s" % (n, p["surface"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
