# Generated by matugen — do not edit
set -g matugen_primary   {{colors.primary.default.hex_stripped}}
set -g matugen_surface   {{colors.surface.default.hex_stripped}}

set -U fish_color_normal        {{colors.on_surface.default.hex_stripped}}
set -U fish_color_command       {{colors.primary.default.hex_stripped}}
set -U fish_color_keyword       {{colors.tertiary.default.hex_stripped}}
set -U fish_color_quote         {{colors.secondary.default.hex_stripped}}
set -U fish_color_redirection   {{colors.tertiary.default.hex_stripped}}
set -U fish_color_end           {{colors.on_surface_variant.default.hex_stripped}}
set -U fish_color_error         {{colors.error.default.hex_stripped}}
set -U fish_color_param         {{colors.on_surface_variant.default.hex_stripped}}
set -U fish_color_comment       {{colors.outline.default.hex_stripped}}
set -U fish_color_selection     --background={{colors.primary_container.default.hex_stripped}}
set -U fish_color_search_match  --background={{colors.primary_container.default.hex_stripped}}
set -U fish_color_operator      {{colors.tertiary.default.hex_stripped}}
set -U fish_color_escape        {{colors.tertiary.default.hex_stripped}}
set -U fish_color_autosuggestion {{colors.outline.default.hex_stripped}}
set -U fish_color_cancel        {{colors.error.default.hex_stripped}}
set -U fish_color_valid_path    --underline
set -U fish_pager_color_progress      {{colors.on_surface_variant.default.hex_stripped}}
set -U fish_pager_color_prefix        {{colors.primary.default.hex_stripped}}
set -U fish_pager_color_completion    {{colors.on_surface.default.hex_stripped}}
set -U fish_pager_color_description   {{colors.outline.default.hex_stripped}}
set -U fish_pager_color_selected_background --background={{colors.primary_container.default.hex_stripped}}
