# Generated by matugen — sourced by theme_changer.sh
# Must match how ~/.config/hypr/visuals.lua builds these from colors.lua.
M_ACTIVE_BORDER="rgba({{colors.primary.default.hex_stripped}}99)"
# Второй цвет градиента активной рамки — его вращает анимация borderangle.
M_ACTIVE_BORDER2="rgba({{colors.secondary.default.hex_stripped}}66)"
# Неактивная рамка — тот же акцент, что у активной, но сильно прозрачный.
# Раньше здесь был surface (почти цвет фона), из-за чего неактивные окна
# выглядели вовсе без рамки; 55 — примерно треть непрозрачности, рамка
# читается, но не спорит с активным окном.
M_INACTIVE_BORDER="rgba({{colors.primary.default.hex_stripped}}22)"
