# Generated by matugen — input for gen_term_colors.py
ACCENT_HUE={{colors.primary.default.hue}}
ACCENT_SAT={{colors.primary.default.saturation}}
ACCENT_LIGHT={{colors.primary.default.lightness}}
ACCENT_HEX={{colors.primary.default.hex}}
ON_ACCENT={{colors.on_primary.default.hex}}
SURFACE={{colors.surface.default.hex}}
SURFACE_LOWEST={{colors.surface_container_lowest.default.hex}}
ON_SURFACE={{colors.on_surface.default.hex}}
ON_SURFACE_VARIANT={{colors.on_surface_variant.default.hex}}
OUTLINE={{colors.outline.default.hex}}
PRIMARY_CONTAINER={{colors.primary_container.default.hex}}
ON_PRIMARY_CONTAINER={{colors.on_primary_container.default.hex}}
TERTIARY={{colors.tertiary.default.hex}}
TERTIARY_HUE={{colors.tertiary.default.hue}}
